# Generated by Django 5.0.1 on 2024-02-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Name', models.CharField(max_length=50)),
                ('Employee_Age', models.IntegerField()),
                ('Employee_pic', models.ImageField(null=True, upload_to='uploadedimages/')),
                ('Employee_joining_date', models.DateField()),
                ('Last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
